- name: Apply Security Patches to CentOS Servers
  hosts: webservers
  become: yes

  tasks:

    - name: Apply security updates using dnf
      when: ansible_facts['distribution_major_version'] | int >= 8
      dnf:
        name: '*'
        state: latest
        security: yes

    - name: Install yum-plugin-security for CentOS 7
      when: ansible_facts['distribution_major_version'] | int == 7
      yum:
        name: yum-plugin-security
        state: present

    - name: Apply security updates using yum for CentOS 7
      when: ansible_facts['distribution_major_version'] | int == 7
      yum:
        name: '*'
        state: latest
        security: yes

    - name: Reboot if kernel was updated (optional)
      reboot:
        msg: "Rebooting after security patching"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: ansible_facts.packages['kernel'][0]['version'] is defined
